using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace Orizon.UI.TagHelpers;

[HtmlTargetElement("orizon-dashboard-grid")]
public sealed class OrizonDashboardGridTagHelper:TagHelper
{
 [HtmlAttributeName("columns")]public int Columns{get;set;}=12;[HtmlAttributeName("gap")]public string Gap{get;set;}="var(--orizon-space-4)";[HtmlAttributeName("responsive")]public bool Responsive{get;set;}=true;[HtmlAttributeName("auto-fit")]public bool AutoFit{get;set;}[HtmlAttributeName("auto-fill")]public bool AutoFill{get;set;}[HtmlAttributeName("min-widget-width")]public string MinWidgetWidth{get;set;}="18rem";
 public override async Task ProcessAsync(TagHelperContext context,TagHelperOutput output){var content=await output.GetChildContentAsync();var cls=output.Attributes["class"]?.Value?.ToString();output.Attributes.Clear();output.TagName="div";output.TagMode=TagMode.StartTagAndEndTag;output.Attributes.SetAttribute("class",TagHelperClassBuilder.Build("orizon-dashboard-grid",Responsive?"is-responsive":null,AutoFit?"is-auto-fit":null,AutoFill?"is-auto-fill":null,cls));output.Attributes.SetAttribute("style",$"--dashboard-columns:{Math.Clamp(Columns,1,24)};--dashboard-gap:{Gap};--dashboard-min-widget:{MinWidgetWidth}");output.Content.SetHtmlContent(content);}
}

[HtmlTargetElement("orizon-dashboard-widget")]
public sealed class OrizonDashboardWidgetTagHelper:TagHelper
{
 [HtmlAttributeName("title")]public string Title{get;set;}="Widget";[HtmlAttributeName("subtitle")]public string? Subtitle{get;set;}[HtmlAttributeName("icon")]public string? Icon{get;set;}[HtmlAttributeName("loading")]public bool Loading{get;set;}[HtmlAttributeName("empty")]public bool Empty{get;set;}[HtmlAttributeName("error")]public string? Error{get;set;}[HtmlAttributeName("refresh")]public bool Refresh{get;set;}[HtmlAttributeName("collapsible")]public bool Collapsible{get;set;}[HtmlAttributeName("collapsed")]public bool Collapsed{get;set;}[HtmlAttributeName("fullscreen")]public bool Fullscreen{get;set;}[HtmlAttributeName("column-span")]public int ColumnSpan{get;set;}=4;[HtmlAttributeName("row-span")]public int RowSpan{get;set;}=1;[HtmlAttributeName("footer")]public string? Footer{get;set;}
 public override async Task ProcessAsync(TagHelperContext context,TagHelperOutput output){var e=HtmlEncoder.Default;var content=await output.GetChildContentAsync();var id=output.Attributes["id"]?.Value?.ToString()??$"orizon-widget-{context.UniqueId.Replace("__","")}";var cls=output.Attributes["class"]?.Value?.ToString();output.Attributes.Clear();output.TagName="article";output.TagMode=TagMode.StartTagAndEndTag;output.Attributes.SetAttribute("id",id);output.Attributes.SetAttribute("class",TagHelperClassBuilder.Build("orizon-dashboard-widget",Collapsed?"is-collapsed":null,Loading?"is-loading":null,cls));output.Attributes.SetAttribute("data-dashboard-widget","");output.Attributes.SetAttribute("style",$"--widget-column-span:{Math.Clamp(ColumnSpan,1,24)};--widget-row-span:{Math.Clamp(RowSpan,1,8)}");if(Loading)output.Attributes.SetAttribute("aria-busy","true");var actions=$"{(Refresh?"<button type=\"button\" data-widget-refresh aria-label=\"Atualizar widget\">↻</button>":"")}{(Collapsible?$"<button type=\"button\" data-widget-collapse aria-label=\"{(Collapsed?"Expandir":"Recolher")} widget\" aria-expanded=\"{(!Collapsed).ToString().ToLowerInvariant()}\">⌃</button>":"")}{(Fullscreen?"<button type=\"button\" data-widget-fullscreen aria-label=\"Exibir widget em tela cheia\">⛶</button>":"")}";string body=Loading?"<span class=\"orizon-skeleton orizon-skeleton--card is-animated\" aria-hidden=\"true\"></span>":Error is not null?$"<div class=\"orizon-dashboard-widget__state is-error\" role=\"alert\"><strong>Erro ao carregar</strong><span>{e.Encode(Error)}</span></div>":Empty?"<div class=\"orizon-dashboard-widget__state\"><strong>Sem dados</strong><span>Não há informações para este período.</span></div>":content.GetContent();output.Content.SetHtmlContent($"<header><div class=\"orizon-dashboard-widget__heading\">{(Icon is null?"":$"<span aria-hidden=\"true\"><i class=\"ph ph-{e.Encode(Icon)}\"></i></span>")}<div><h2>{e.Encode(Title)}</h2>{(Subtitle is null?"":$"<p>{e.Encode(Subtitle)}</p>")}</div></div><div class=\"orizon-dashboard-widget__actions\">{actions}</div></header><div class=\"orizon-dashboard-widget__body\"{(Collapsed?" hidden":"")}>{body}</div>{(Footer is null?"":$"<footer>{e.Encode(Footer)}</footer>")}");}
}
