using System.Globalization;
using System.Text.Encodings.Web;
using System.Text.Json;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Orizon.UI.Charts;

namespace Orizon.UI.TagHelpers;

[HtmlTargetElement("orizon-progress-ring")]
public sealed class OrizonProgressRingTagHelper:TagHelper
{
 [HtmlAttributeName("value")]public double Value{get;set;}[HtmlAttributeName("min")]public double Min{get;set;}[HtmlAttributeName("max")]public double Max{get;set;}=100;[HtmlAttributeName("size")]public int Size{get;set;}=120;[HtmlAttributeName("thickness")]public int Thickness{get;set;}=10;[HtmlAttributeName("label")]public string? Label{get;set;}[HtmlAttributeName("animated")]public bool Animated{get;set;}=true;[HtmlAttributeName("status")]public string Status{get;set;}="primary";
 public override void Process(TagHelperContext context,TagHelperOutput output){var range=Math.Max(.0001,Max-Min);var ratio=Math.Clamp((Value-Min)/range,0,1);var radius=45d;var circumference=2*Math.PI*radius;var offset=circumference*(1-ratio);var value=Value.ToString("0.##",CultureInfo.InvariantCulture);output.TagName="div";output.TagMode=TagMode.StartTagAndEndTag;output.Attributes.SetAttribute("class",TagHelperClassBuilder.Build("orizon-progress-ring",$"orizon-progress-ring--{Status}",Animated?"is-animated":null));output.Attributes.SetAttribute("role","progressbar");output.Attributes.SetAttribute("aria-valuemin",Min);output.Attributes.SetAttribute("aria-valuemax",Max);output.Attributes.SetAttribute("aria-valuenow",Value);output.Attributes.SetAttribute("aria-label",Label??"Progresso");output.Attributes.SetAttribute("style",$"--ring-size:{Math.Clamp(Size,48,320)}px;--ring-thickness:{Math.Clamp(Thickness,3,28)}px;--ring-offset:{offset.ToString("0.##",CultureInfo.InvariantCulture)};--ring-circumference:{circumference.ToString("0.##",CultureInfo.InvariantCulture)}");output.Content.SetHtmlContent($"<svg viewBox=\"0 0 100 100\" aria-hidden=\"true\"><circle class=\"orizon-progress-ring__track\" cx=\"50\" cy=\"50\" r=\"45\"/><circle class=\"orizon-progress-ring__value\" cx=\"50\" cy=\"50\" r=\"45\"/></svg><span><strong>{value}</strong>{(Label is null?"":$"<small>{HtmlEncoder.Default.Encode(Label)}</small>")}</span>");}
}

[HtmlTargetElement("orizon-gauge")]
public sealed class OrizonGaugeTagHelper:TagHelper
{
 [HtmlAttributeName("min")]public double Min{get;set;}[HtmlAttributeName("max")]public double Max{get;set;}=100;[HtmlAttributeName("value")]public double Value{get;set;}[HtmlAttributeName("ranges")]public string? Ranges{get;set;}[HtmlAttributeName("needle")]public bool Needle{get;set;}=true;[HtmlAttributeName("label")]public string? Label{get;set;}[HtmlAttributeName("unit")]public string? Unit{get;set;}[HtmlAttributeName("ticks")]public int Ticks{get;set;}=5;
 public override void Process(TagHelperContext context,TagHelperOutput output){var e=HtmlEncoder.Default;var ratio=Math.Clamp((Value-Min)/Math.Max(.001,Max-Min),0,1);var angle=-90+ratio*180;var ticks=string.Join("",Enumerable.Range(0,Math.Clamp(Ticks,2,12)).Select(i=>{var a=(-180+i*180d/(Math.Clamp(Ticks,2,12)-1))*Math.PI/180;var x1=100+82*Math.Cos(a);var y1=100+82*Math.Sin(a);var x2=100+90*Math.Cos(a);var y2=100+90*Math.Sin(a);return $"<line x1=\"{N(x1)}\" y1=\"{N(y1)}\" x2=\"{N(x2)}\" y2=\"{N(y2)}\"/>";}));output.TagName="div";output.TagMode=TagMode.StartTagAndEndTag;output.Attributes.SetAttribute("class","orizon-gauge");output.Attributes.SetAttribute("role","meter");output.Attributes.SetAttribute("aria-valuemin",Min);output.Attributes.SetAttribute("aria-valuemax",Max);output.Attributes.SetAttribute("aria-valuenow",Value);output.Attributes.SetAttribute("aria-label",Label??"Indicador");output.Attributes.SetAttribute("data-ranges",Ranges??"[]");output.Content.SetHtmlContent($"<svg viewBox=\"0 0 200 120\" aria-hidden=\"true\"><path class=\"orizon-gauge__track\" d=\"M 15 100 A 85 85 0 0 1 185 100\"/><path class=\"orizon-gauge__value\" pathLength=\"100\" stroke-dasharray=\"{N(ratio*100)} 100\" d=\"M 15 100 A 85 85 0 0 1 185 100\"/><g class=\"orizon-gauge__ticks\">{ticks}</g>{(Needle?$"<g class=\"orizon-gauge__needle\" style=\"transform:rotate({N(angle)}deg)\"><line x1=\"100\" y1=\"100\" x2=\"172\" y2=\"100\"/><circle cx=\"100\" cy=\"100\" r=\"6\"/></g>":"")}</svg><div><strong>{N(Value)}{e.Encode(Unit??"")}</strong>{(Label is null?"":$"<span>{e.Encode(Label)}</span>")}</div>");}
 private static string N(double value)=>value.ToString("0.##",CultureInfo.InvariantCulture);
}

[HtmlTargetElement("orizon-metric-card")]
public sealed class OrizonMetricCardTagHelper:TagHelper
{
 [HtmlAttributeName("title")]public string Title{get;set;}="Métrica";[HtmlAttributeName("value")]public string Value{get;set;}="—";[HtmlAttributeName("previous")]public string? Previous{get;set;}[HtmlAttributeName("variation")]public string? Variation{get;set;}[HtmlAttributeName("trend")]public string Trend{get;set;}="neutral";[HtmlAttributeName("icon")]public string? Icon{get;set;}[HtmlAttributeName("sparkline")]public string? Sparkline{get;set;}[HtmlAttributeName("footer")]public string? Footer{get;set;}[HtmlAttributeName("helper")]public string? Helper{get;set;}[HtmlAttributeName("loading")]public bool Loading{get;set;}[HtmlAttributeName("compact")]public bool Compact{get;set;}
 public override void Process(TagHelperContext context,TagHelperOutput output){var e=HtmlEncoder.Default;output.TagName="article";output.TagMode=TagMode.StartTagAndEndTag;output.Attributes.SetAttribute("class",TagHelperClassBuilder.Build("orizon-metric-card",$"orizon-metric-card--{Trend}",Compact?"is-compact":null,Loading?"is-loading":null));if(Loading){output.Attributes.SetAttribute("aria-busy","true");output.Content.SetHtmlContent("<span class=\"orizon-skeleton orizon-skeleton--text is-animated\"></span><span class=\"orizon-skeleton orizon-skeleton--rectangle is-animated\"></span>");return;}IReadOnlyList<double> values;try{values=JsonSerializer.Deserialize<double[]>(Sparkline??"[]")??[];}catch(JsonException){values=[];}var trendLabel=Trend=="positive"?"Aumento":Trend=="negative"?"Redução":"Estável";output.Content.SetHtmlContent($"<header>{(Icon is null?"":$"<span class=\"orizon-metric-card__icon\" aria-hidden=\"true\"><i class=\"ph ph-{e.Encode(Icon)}\"></i></span>")}<div><span>{e.Encode(Title)}</span>{(Helper is null?"":$"<small>{e.Encode(Helper)}</small>")}</div></header><div class=\"orizon-metric-card__value\"><strong>{e.Encode(Value)}</strong>{(Variation is null?"":$"<span><span class=\"orizon-visually-hidden\">{trendLabel}: </span>{e.Encode(Variation)}</span>")}</div>{(values.Count==0?"":$"<div class=\"orizon-metric-card__sparkline\">{ChartSvgEngine.Sparkline(values,"area","var(--metric-accent)")}</div>")}{(Previous is null?"":$"<p>Anterior: {e.Encode(Previous)}</p>")}{(Footer is null?"":$"<footer>{e.Encode(Footer)}</footer>")}");}
}
