using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace Orizon.UI.TagHelpers;

[HtmlTargetElement("orizon-command-bar")]
public sealed class OrizonCommandBarTagHelper:TagHelper
{
 [HtmlAttributeName("title")]public string Title{get;set;}="Página";[HtmlAttributeName("subtitle")]public string? Subtitle{get;set;}[HtmlAttributeName("breadcrumb")]public string? Breadcrumb{get;set;}[HtmlAttributeName("search")]public bool Search{get;set;}[HtmlAttributeName("search-placeholder")]public string SearchPlaceholder{get;set;}="Pesquisar...";[HtmlAttributeName("primary-text")]public string? PrimaryText{get;set;}[HtmlAttributeName("primary-href")]public string? PrimaryHref{get;set;}[HtmlAttributeName("sticky")]public bool Sticky{get;set;}[HtmlAttributeName("keyboard")]public bool Keyboard{get;set;}=true;
 public override async Task ProcessAsync(TagHelperContext context,TagHelperOutput output){var e=HtmlEncoder.Default;var content=await output.GetChildContentAsync();var cls=output.Attributes["class"]?.Value?.ToString();output.Attributes.Clear();output.TagName="header";output.TagMode=TagMode.StartTagAndEndTag;output.Attributes.SetAttribute("class",TagHelperClassBuilder.Build("orizon-command-bar",Sticky?"is-sticky":null,cls));output.Attributes.SetAttribute("data-orizon-command-bar","");if(Keyboard)output.Attributes.SetAttribute("data-command-keyboard","true");var primary=PrimaryText is null?"":PrimaryHref is null?$"<button class=\"orizon-button orizon-button--solid orizon-button--primary\" type=\"button\" data-command-primary>{e.Encode(PrimaryText)}</button>":$"<a class=\"orizon-button orizon-button--solid orizon-button--primary\" href=\"{e.Encode(PrimaryHref)}\">{e.Encode(PrimaryText)}</a>";output.Content.SetHtmlContent($"<div class=\"orizon-command-bar__identity\">{(Breadcrumb is null?"":$"<nav aria-label=\"Breadcrumb\">{e.Encode(Breadcrumb)}</nav>")}<div><h1>{e.Encode(Title)}</h1>{(Subtitle is null?"":$"<p>{e.Encode(Subtitle)}</p>")}</div></div><div class=\"orizon-command-bar__tools\">{(Search?$"<label class=\"orizon-command-bar__search\"><span class=\"orizon-visually-hidden\">Pesquisar</span><input type=\"search\" placeholder=\"{e.Encode(SearchPlaceholder)}\" data-command-search><kbd>/</kbd></label>":"")}<div class=\"orizon-command-bar__actions\" data-command-actions>{content.GetContent()}</div>{primary}</div>");}
}

[HtmlTargetElement("orizon-command-palette")]
public sealed class OrizonCommandPaletteTagHelper:TagHelper
{
 [HtmlAttributeName("id")]public string? Id{get;set;}[HtmlAttributeName("title")]public string Title{get;set;}="Central de comandos";[HtmlAttributeName("placeholder")]public string Placeholder{get;set;}="Digite um comando...";[HtmlAttributeName("shortcut")]public string Shortcut{get;set;}="Ctrl+K";[HtmlAttributeName("empty-text")]public string EmptyText{get;set;}="Nenhum comando encontrado";[HtmlAttributeName("open")]public bool Open{get;set;}
 public override async Task ProcessAsync(TagHelperContext context,TagHelperOutput output){var e=HtmlEncoder.Default;var content=await output.GetChildContentAsync();var id=Id??$"orizon-command-palette-{context.UniqueId.Replace("__","")}";var titleId=$"{id}-title";output.Attributes.Clear();output.TagName="div";output.TagMode=TagMode.StartTagAndEndTag;output.Attributes.SetAttribute("id",id);output.Attributes.SetAttribute("class",TagHelperClassBuilder.Build("orizon-command-palette",Open?"is-open":null));output.Attributes.SetAttribute("data-orizon-command-palette","");output.Attributes.SetAttribute("data-shortcut",Shortcut);output.Attributes.SetAttribute("role","dialog");output.Attributes.SetAttribute("aria-modal","true");output.Attributes.SetAttribute("aria-labelledby",titleId);if(!Open)output.Attributes.SetAttribute("hidden","hidden");output.Content.SetHtmlContent($"<div class=\"orizon-command-palette__backdrop\" data-command-close></div><div class=\"orizon-command-palette__panel\"><header><h2 class=\"orizon-visually-hidden\" id=\"{e.Encode(titleId)}\">{e.Encode(Title)}</h2><span aria-hidden=\"true\">⌕</span><input type=\"search\" placeholder=\"{e.Encode(Placeholder)}\" aria-label=\"Pesquisar comandos\" role=\"combobox\" aria-expanded=\"true\" aria-controls=\"{e.Encode(id)}-list\" data-command-input><kbd>Esc</kbd></header><div class=\"orizon-command-palette__list\" id=\"{e.Encode(id)}-list\" role=\"listbox\" data-command-list>{content.GetContent()}<p class=\"orizon-command-palette__empty\" data-command-empty hidden>{e.Encode(EmptyText)}</p></div><footer><span>↑↓ navegar</span><span>Enter selecionar</span><span>{e.Encode(Shortcut)} abrir</span></footer></div>");}
}
