using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace Orizon.UI.TagHelpers;

[HtmlTargetElement("orizon-drawer")]
public sealed class OrizonDrawerTagHelper:TagHelper
{
 [HtmlAttributeName("id")]public string? Id{get;set;}[HtmlAttributeName("title")]public string Title{get;set;}="Painel";[HtmlAttributeName("position")]public string Position{get;set;}="right";[HtmlAttributeName("overlay")]public bool Overlay{get;set;}=true;[HtmlAttributeName("persistent")]public bool Persistent{get;set;}[HtmlAttributeName("responsive")]public bool Responsive{get;set;}=true;[HtmlAttributeName("open")]public bool Open{get;set;}[HtmlAttributeName("width")]public string Width{get;set;}="24rem";
 public override async Task ProcessAsync(TagHelperContext context,TagHelperOutput output){var e=HtmlEncoder.Default;var content=await output.GetChildContentAsync();var id=Id??$"orizon-drawer-{context.UniqueId.Replace("__","")}";var titleId=$"{id}-title";output.Attributes.Clear();output.TagName="aside";output.TagMode=TagMode.StartTagAndEndTag;output.Attributes.SetAttribute("id",id);output.Attributes.SetAttribute("class",TagHelperClassBuilder.Build("orizon-drawer",$"orizon-drawer--{Position}",Open?"is-open":null,Persistent?"is-persistent":null,Responsive?"is-responsive":null));output.Attributes.SetAttribute("data-orizon-drawer","");output.Attributes.SetAttribute("data-persistent",Persistent.ToString().ToLowerInvariant());output.Attributes.SetAttribute("role","dialog");output.Attributes.SetAttribute("aria-modal",(!Persistent).ToString().ToLowerInvariant());output.Attributes.SetAttribute("aria-labelledby",titleId);output.Attributes.SetAttribute("style",$"--drawer-size:{Width}");if(!Open&&!Persistent)output.Attributes.SetAttribute("hidden","hidden");output.Content.SetHtmlContent($"{(Overlay&&!Persistent?"<div class=\"orizon-drawer__overlay\" data-drawer-close></div>":"")}<div class=\"orizon-drawer__panel\"><header><h2 id=\"{e.Encode(titleId)}\">{e.Encode(Title)}</h2><button type=\"button\" data-drawer-close aria-label=\"Fechar painel\">&times;</button></header><div class=\"orizon-drawer__content\">{content.GetContent()}</div></div>");}
}

[HtmlTargetElement("orizon-split-view")]
public sealed class OrizonSplitViewTagHelper:TagHelper
{
 [HtmlAttributeName("orientation")]public string Orientation{get;set;}="horizontal";[HtmlAttributeName("initial-size")]public int InitialSize{get;set;}=35;[HtmlAttributeName("min-size")]public int MinSize{get;set;}=15;[HtmlAttributeName("max-size")]public int MaxSize{get;set;}=80;[HtmlAttributeName("resizable")]public bool Resizable{get;set;}=true;[HtmlAttributeName("collapsible")]public bool Collapsible{get;set;}[HtmlAttributeName("persist-key")]public string? PersistKey{get;set;}
 public override async Task ProcessAsync(TagHelperContext context,TagHelperOutput output){var content=await output.GetChildContentAsync();output.TagName="div";output.TagMode=TagMode.StartTagAndEndTag;output.Attributes.SetAttribute("class",TagHelperClassBuilder.Build("orizon-split-view",$"orizon-split-view--{Orientation}",Resizable?"is-resizable":null));output.Attributes.SetAttribute("data-orizon-split-view","");output.Attributes.SetAttribute("data-orientation",Orientation);output.Attributes.SetAttribute("data-min",Math.Clamp(MinSize,5,90));output.Attributes.SetAttribute("data-max",Math.Clamp(MaxSize,10,95));if(PersistKey is not null)output.Attributes.SetAttribute("data-persist-key",PersistKey);output.Attributes.SetAttribute("style",$"--split-primary:{Math.Clamp(InitialSize,MinSize,MaxSize)}%");output.Content.SetHtmlContent($"<div class=\"orizon-split-view__panes\">{content.GetContent()}</div>{(Resizable?$"<div class=\"orizon-split-view__separator\" role=\"separator\" tabindex=\"0\" aria-orientation=\"{(Orientation=="vertical"?"horizontal":"vertical")}\" aria-valuemin=\"{MinSize}\" aria-valuemax=\"{MaxSize}\" aria-valuenow=\"{InitialSize}\" data-split-handle>{(Collapsible?"<button type=\"button\" data-split-collapse aria-label=\"Recolher painel principal\">‹</button>":"")}</div>":"")}");}
}
